// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.function {
    exports com.mastfrog.function;
    exports com.mastfrog.function.state;
    exports com.mastfrog.function.throwing;
    exports com.mastfrog.function.throwing.io;

    // Inferred from source scan

    // Sibling com.mastfrog/util-preconditions-3.0.0-dev
    requires com.mastfrog.preconditions;

    // Inferred from test-source-scan
    requires transitive org.junit.jupiter.api;

}
