open module com.mastfrog.util.streams {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.util.file;
    exports com.mastfrog.util.path;
    exports com.mastfrog.util.streams;
    exports com.mastfrog.util.streams.stdio;
    requires transitive com.mastfrog.function;
    requires transitive com.mastfrog.util.preconditions;
    requires java.logging;
}
