// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.range {
    exports com.mastfrog.range;

    // derived from org.netbeans.api/org-netbeans-api-annotations-common-0.0.0-?:provided in org/netbeans/api/org-netbeans-api-annotations-common/RELEASE126/org-netbeans-api-annotations-common-RELEASE126.pom
    requires transitive org.netbeans.api.annotations.common.RELEASE126;

}
