open module com.mastfrog.range {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.range;

    // derived from org.netbeans.api/org-netbeans-api-annotations-common-RELEASE126:provided in org/netbeans/api/org-netbeans-api-annotations-common/RELEASE126/org-netbeans-api-annotations-common-RELEASE126.pom
//    requires transitive org.netbeans.api.org.netbeans.api.annotations.common;

}
