open module com.mastfrog.search {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.util.search;
    requires com.mastfrog.abstractions;
    requires com.mastfrog.util.preconditions;
}
