open module com.mastfrog.predicates {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.predicates;
    exports com.mastfrog.predicates.integer;
    exports com.mastfrog.predicates.pattern;
    exports com.mastfrog.predicates.string;
    requires transitive com.mastfrog.abstractions;
    requires transitive com.mastfrog.function;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit;
}
