// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.predicates {
    exports com.mastfrog.predicates;
    exports com.mastfrog.predicates.integer;
    exports com.mastfrog.predicates.pattern;
    exports com.mastfrog.predicates.string;

    // Inferred from source scan

    // Sibling com.mastfrog/abstractions-3.0.0-dev
    requires com.mastfrog.abstractions;

    // Inferred from source scan

    // Sibling com.mastfrog/function-3.0.0-dev

    // Transitive detected by source scan
    requires com.mastfrog.function;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from test-source-scan
    requires transitive junit;

}
