module com.mastfrog.annotation.processors {
// Generated by com.dv.sourcetreetool.impl.App

//    provides com.mastfrog.util.service.ServiceProviderAnnotationProcessor;
    exports com.mastfrog.util.service;
    requires transitive com.mastfrog.annotation.tools;

    provides javax.annotation.processing.Processor 
            with com.mastfrog.util.service.ServiceProviderAnnotationProcessor;
    
    requires java.compiler;
    // derived from org.netbeans.api/org-openide-filesystems-RELEASE126 in org/netbeans/api/org-openide-filesystems/RELEASE126/org-openide-filesystems-RELEASE126.pom
}
