// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.annotation.processors {
    exports com.mastfrog.util.service;

    requires com.mastfrog.annotation.tools;
    requires java.compiler;

    provides javax.annotation.processing.Processor 
            with com.mastfrog.util.service.ServiceProviderAnnotationProcessor;
}
