// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.graph {
    exports com.mastfrog.graph;
    exports com.mastfrog.graph.algorithm;
    exports com.mastfrog.graph.dynamic;

    // Inferred from source scan

    // Sibling com.mastfrog/abstractions-3.0.0-dev
    requires com.mastfrog.abstractions;

    // Sibling com.mastfrog/bits-3.0.0-dev
    requires com.mastfrog.bits;

    // Inferred from source scan

    // Sibling com.mastfrog/function-3.0.0-dev
    requires com.mastfrog.function;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from test-source-scan
    requires transitive org.junit.jupiter.api;

}
