// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.annotation.processors {
    exports com.mastfrog.util.service;

    // Sibling com.mastfrog/annotation-tools-3.0.0-dev

    // Transitive detected by source scan
    requires com.mastfrog.annotation.tools;
    requires java.compiler;

    // Inferred from test-source-scan
    requires junit;
    
    provides javax.annotation.processing.Processor 
            with com.mastfrog.util.service.ServiceProviderAnnotationProcessor;    

    provides com.mastfrog.util.service.AbstractWoogle with
       com.mastfrog.util.service.AnotherWoogle,
       com.mastfrog.util.service.ConcreteWoogle,
       com.mastfrog.util.service.YetAnotherWoogle;
    
    uses com.mastfrog.util.service.AbstractWoogle;
}
