module com.mastfrog.annotation.processors {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.util.service;
    requires transitive com.mastfrog.annotation.tools;

    provides javax.annotation.processing.Processor 
            with com.mastfrog.util.service.ServiceProviderAnnotationProcessor;
    
    requires java.compiler;
    requires junit;
    uses com.mastfrog.util.service.AbstractWoogle;
//    requires org.openide.filesystems.RELEASE126;    
}
