// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.file.channel.pool {
    exports com.mastfrog.file.channels;

    // Sibling com.mastfrog/cache-3.0.0-dev
    requires com.mastfrog.cache;

    // Inferred from source scan

    // Sibling com.mastfrog/util-collections-3.0.0-dev
    requires com.mastfrog.collections;

    // Inferred from source scan

    // Sibling com.mastfrog/function-3.0.0-dev

    // Transitive detected by source scan
    requires com.mastfrog.function;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan
    requires com.mastfrog.streams;

    // Inferred from source scan
    requires com.mastfrog.util.function;
    requires java.logging;

    // Inferred from test-source-scan
    requires transitive org.junit.jupiter.api;

}
