open module com.mastfrog.util.function {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.util.function;
    exports com.mastfrog.util.multivariate;
    exports com.mastfrog.util.thread;
    requires transitive com.mastfrog.abstractions;
    requires transitive com.mastfrog.function;
    requires transitive com.mastfrog.util.preconditions;
}
