// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.search {
    exports com.mastfrog.util.search;

    // Inferred from source scan

    // Sibling com.mastfrog/abstractions-3.0.0-dev
    requires com.mastfrog.abstractions;

    // Inferred from source scan

    // Sibling com.mastfrog/util-preconditions-3.0.0-dev
    requires com.mastfrog.preconditions;

    // Inferred from test-source-scan
    requires transitive junit;

}
