// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.subscription {
    exports com.mastfrog.subscription;

    // Sibling com.mastfrog/cache-3.0.0-dev

    // Transitive detected by source scan
    requires com.mastfrog.cache;

    // Inferred from source scan

    // Sibling com.mastfrog/util-collections-3.0.0-dev
    requires com.mastfrog.collections;

    // Inferred from source scan

    // Sibling com.mastfrog/function-3.0.0-dev
    requires com.mastfrog.function;

    // Inferred from source scan

    // Sibling com.mastfrog/util-preconditions-3.0.0-dev
    requires com.mastfrog.preconditions;

}
