open module com.mastfrog.subscription {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.subscription;
    requires transitive com.mastfrog.cache;
    requires transitive com.mastfrog.function;
    requires transitive com.mastfrog.util.collections;
    requires transitive com.mastfrog.util.preconditions;

}
