// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.misc {
    exports com.mastfrog.util.codec;
    exports com.mastfrog.util.libversion;
    exports com.mastfrog.util.perf;

    // Inferred from source scan

    // Transitive detected by source scan
    requires com.mastfrog.strings;
    requires java.logging;

    // Inferred from test-source-scan
    requires transitive org.junit.jupiter.api;

    // Inferred from test-source-scan
    requires transitive org.junit.jupiter.params;

}
