// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.preconditions {
    exports com.mastfrog.util.preconditions;
    requires java.logging;
    uses com.mastfrog.util.preconditions.Exceptions.ExceptionHandler;
}
