import com.mastfrog.util.preconditions.Exceptions;

open module com.mastfrog.util.preconditions {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.util.preconditions;
    requires java.logging;
    uses Exceptions.ExceptionHandler;
}
