// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.concurrent {
    exports com.mastfrog.concurrent;
    exports com.mastfrog.concurrent.lock;
    exports com.mastfrog.concurrent.stats;

    // Inferred from source scan

    // Sibling com.mastfrog/function-3.0.0-dev
    requires com.mastfrog.function;

    // Inferred from source scan

    // Sibling com.mastfrog/util-preconditions-3.0.0-dev
    requires com.mastfrog.preconditions;
    requires java.logging;

    // Inferred from test-source-scan
    requires transitive org.junit.jupiter.api;

}
