// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.time {
    exports com.mastfrog.util.time;

    // Inferred from source scan

    // Sibling com.mastfrog/util-preconditions-3.0.0-dev
    requires com.mastfrog.preconditions;

}
