// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.fileformat {
    exports com.mastfrog.util.fileformat;

    // Inferred from source scan

    // Transitive detected by source scan
    requires com.mastfrog.collections;

    // Inferred from source scan
    requires com.mastfrog.strings;
    requires java.logging;

    // Inferred from test-source-scan
    requires transitive junit;

}
