open module com.mastfrog.abstractions {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.abstractions;
    exports com.mastfrog.abstractions.list;
    exports com.mastfrog.abstractions.misc;

}
