// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.util.function {
    exports com.mastfrog.util.function;
    exports com.mastfrog.util.multivariate;
    exports com.mastfrog.util.thread;

    // Sibling com.mastfrog/abstractions-3.0.0-dev
    requires com.mastfrog.abstractions;

    // Inferred from source scan

    // Sibling com.mastfrog/function-3.0.0-dev
    requires com.mastfrog.function;

    // Inferred from source scan

    // Sibling com.mastfrog/util-preconditions-3.0.0-dev
    requires com.mastfrog.preconditions;
    requires java.logging;

    // Inferred from test-source-scan
    requires transitive junit;

}
