// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.converters {
    exports com.mastfrog.converters;

    // Sibling com.mastfrog/graph-3.0.0-dev

    // Transitive detected by source scan
    requires com.mastfrog.graph;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from test-source-scan
    requires transitive org.junit.jupiter.api;

}
