// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.misc {
    exports com.mastfrog.util.codec;
    exports com.mastfrog.util.libversion;
    exports com.mastfrog.util.perf;
    requires java.logging;

}
