open module com.mastfrog.util.misc {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.util.codec;
    exports com.mastfrog.util.libversion;
    exports com.mastfrog.util.perf;
    requires java.logging;
}
