// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.collections {
    exports com.mastfrog.util.collections;

    // Inferred from source scan
    requires com.mastfrog.abstractions;

    // Inferred from source scan

    // Sibling com.mastfrog/util-preconditions-3.0.0-dev
    requires com.mastfrog.preconditions;

    // Sibling com.mastfrog/search-3.0.0-dev

    // Transitive detected by source scan
    requires com.mastfrog.search;

    // Sibling com.mastfrog/sort-3.0.0-dev
    requires com.mastfrog.sort;

    // Inferred from source scan

    // Sibling com.mastfrog/util-strings-3.0.0-dev
    requires com.mastfrog.strings;

}
