open module com.mastfrog.util.collections {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.util.collections;
    requires com.mastfrog.abstractions;
    requires com.mastfrog.search;
    requires com.mastfrog.sort;
    requires com.mastfrog.util.preconditions;
    requires com.mastfrog.util.strings;
}
