// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.bits {
    exports com.mastfrog.bits;
    exports com.mastfrog.bits.collections;
    exports com.mastfrog.bits.large;
    exports com.mastfrog.bits.util;

    // Inferred from source scan

    // Sibling com.mastfrog/abstractions-3.0.0-dev
    requires com.mastfrog.abstractions;

    // Inferred from source scan

    // Sibling com.mastfrog/function-3.0.0-dev
    requires com.mastfrog.function;

    // Inferred from source scan
    requires com.mastfrog.preconditions;
    requires java.logging;
    requires jdk.unsupported;

    // Inferred from test-source-scan
    requires transitive org.junit.jupiter.api;

    // Inferred from test-source-scan
    requires transitive org.junit.jupiter.params;

}
