open module com.mastfrog.graph {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.graph;
    exports com.mastfrog.graph.algorithm;
    exports com.mastfrog.graph.dynamic;
    requires transitive com.mastfrog.abstractions;
    requires transitive com.mastfrog.bits;
    requires transitive com.mastfrog.function;

}
