open module com.mastfrog.bits {
// Generated by com.dv.sourcetreetool.impl.App

    requires jdk.unsupported; // sun.misc.Unsafe

    exports com.mastfrog.bits;
    exports com.mastfrog.bits.collections;
    exports com.mastfrog.bits.large;
    exports com.mastfrog.bits.util;
    requires transitive com.mastfrog.abstractions;
    requires transitive com.mastfrog.function;
    requires java.logging;

}
