open module com.mastfrog.file.channel.pool {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.file.channels;
    requires transitive com.mastfrog.cache;
//    requires transitive com.mastfrog.function;
    requires transitive com.mastfrog.util.collections;
    requires com.mastfrog.function;
//    requires transitive com.mastfrog.util.function;
//    requires transitive com.mastfrog.util.streams;
    requires java.logging;

}
