open module com.mastfrog.log.structured.storage {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.logstructured;
    requires transitive com.mastfrog.file.channel.pool;
    requires com.mastfrog.function;
    requires com.mastfrog.util.strings;
//    requires transitive com.mastfrog.util.streams;
    requires java.logging;

}
