// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.log.structured.storage {
    exports com.mastfrog.logstructured;

    // Inferred from source scan
    requires com.mastfrog.collections;

    // Sibling com.mastfrog/file-channel-pool-3.0.0-dev
    requires com.mastfrog.file.channel.pool;

    // Inferred from source scan
    requires com.mastfrog.function;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan

    // Transitive detected by source scan
    requires com.mastfrog.strings;
    requires java.logging;

}
