open module com.mastfrog.function {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.function;
    exports com.mastfrog.function.state;
    exports com.mastfrog.function.throwing;
    exports com.mastfrog.function.throwing.io;
    requires transitive com.mastfrog.util.preconditions;

}
