// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.streams {
    exports com.mastfrog.util.file;
    exports com.mastfrog.util.path;
    exports com.mastfrog.util.streams;
    exports com.mastfrog.util.streams.stdio;

    // Inferred from source scan

    // Sibling com.mastfrog/function-3.0.0-dev
    requires com.mastfrog.function;

    // Inferred from source scan

    // Sibling com.mastfrog/util-preconditions-3.0.0-dev
    requires com.mastfrog.preconditions;
    requires java.logging;

    // Inferred from test-source-scan
    requires transitive junit;

}
