open module com.mastfrog.concurrent {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.concurrent;
    exports com.mastfrog.concurrent.lock;
    exports com.mastfrog.concurrent.stats;
    requires transitive com.mastfrog.function;
    requires transitive com.mastfrog.util.preconditions;
    requires java.logging;

}
