// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.cache {
    exports com.mastfrog.util.cache;

    // Inferred from source scan

    // Sibling com.mastfrog/abstractions-3.0.0-dev
    requires com.mastfrog.abstractions;

    // Inferred from source scan

    // Sibling com.mastfrog/util-preconditions-3.0.0-dev
    requires com.mastfrog.preconditions;
    requires java.logging;

}
