open module com.mastfrog.cache {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.util.cache;
    requires transitive com.mastfrog.abstractions;
    requires transitive com.mastfrog.util.preconditions;
    requires java.logging;

}
