// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.net {
    exports com.mastfrog.util.net;

    // Inferred from source scan

    // Sibling com.mastfrog/util-preconditions-3.0.0-dev
    requires com.mastfrog.preconditions;

}
